ProyectoColProfesionales/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoColProfesionales.Models.DB1;

using System.Text;
using System.Security.Cryptography;
using ProyectoColProfesionales.Servicios.Contrato;
using Microsoft.AspNetCore.Authorization;


namespace ProyectoColProfesionales.Controllers
{
    public class PersonaController : Controller
    {
        private readonly DBColProfessionalContext _context;
        private readonly IEmailSender _emailSender;


        public PersonaController(DBColProfessionalContext context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }
        public IActionResult Create()
        {
            return View();
        }

        //encriptacion 
        public static String EncriptarClave(string password)
        {
            StringBuilder sb = new StringBuilder();

            using (SHA256 hash = SHA256Managed.Create())
            {
                Encoding enc = Encoding.UTF8;
                byte[] result = hash.ComputeHash(enc.GetBytes(password));

                foreach (byte b in result)
                {
                    sb.Append(b.ToString("x2"));
                }
                return sb.ToString();
            }
        }

        ///Generar password y Username
        private string GeneratePassword(string baseString)
        {
            Random random = new Random();
            int randomNumber = random.Next(1000, 9999);
            return baseString.Substring(0, Math.Min(4, baseString.Length)) + randomNumber.ToString();
        }
        private string GenerateUserName(string firstName, string lastName)
        {
            Random random = new Random();
            int randomNumber = random.Next(100, 999);
            return $"{firstName.Substring(0, 1).ToLower()}{lastName.ToLower()}{randomNumber}";
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Models.PersonModel person)
        {
            if (ModelState.IsValid)
            {
                //var person = new Person
                //{
                //    Names = Names,
                //    Lastname = Lastname,
                //    SecondLastName = SecondLastName,
                //    IdentityNumber = IdentityNumber,
                //    PhoneNumber = PhoneNumber,
                //    Email = Email,
                //    RegisterDate = DateTime.Now,
                //    Status = 1
                //};
                // Generar el nombre de usuario y la contraseña
                string userName = GenerateUserName(person.Names, person.Lastname); // Usando el email como nombre de usuario
                string rawPassword = GeneratePassword(person.Names); // Generar una contraseña basada en el nombre
                string emailContent = $"Hola {person.Names},<br/>Tu nueva cuenta ha sido creada.<br/>Nombre de usuario: {userName}<br/>Contraseña: {rawPassword}";
                await _emailSender.SendEmailAsync(person.Email, "Detalles de tu cuenta", emailContent);

                Person personCreate = new Person
                {
                    Names = person.Names,
                    Lastname = person.Lastname,
                    SecondLastName = person.SecondLastName,
                    IdentityNumber = person.IdentityNumber,
                    PhoneNumber = person.PhoneNumber,
                    Email = person.Email,
                    RegisterDate = DateTime.Now,
                    Status = 1
                };

                _context.People.Add(personCreate);
                await _context.SaveChangesAsync();

                var user = new User
                {
                    UserName = userName, // O cualquier otra lógica para definir el UserName
                    Password = EncriptarClave(rawPassword), // Deberías tener una manera segura de establecer contraseñas
                    Role = person.Role,
                    IdPerson = personCreate.IdPerson,
                    RegisterDate = DateTime.Now,
                    Status = 1
                };

                _context.Users.Add(user);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Lista));
            }

            // Si llegas aquí, algo salió mal
            return View();
        }

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string Names, string Lastname, string SecondLastName, string IdentityNumber, string PhoneNumber, string Email, string Role)
        {
            if (ModelState.IsValid)
            {
                var person = new Person
                {
                    Names = Names,
                    Lastname = Lastname,
                    SecondLastName = SecondLastName,
                    IdentityNumber = IdentityNumber,
                    PhoneNumber = PhoneNumber,
                    Email = Email,
                    RegisterDate = DateTime.Now,
                    Status = 1
                };

                //_context.Persons.Add(person);
                _context.People.Add(person);
                await _context.SaveChangesAsync();

                var user = new User
                {
                    UserName = "Secretary", // O cualquier otra lógica para definir el UserName
                    Password = "123456", // Deberías tener una manera segura de establecer contraseñas
                    Role = Role,
                    IdPerson = person.IdPerson,
                    RegisterDate = DateTime.Now,
                    Status = 1
                };

                _context.Users.Add(user);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Lista));
            }

            // Si llegas aquí, algo salió mal
            return View();
        }*/

        /* [HttpGet]
         public async Task<IActionResult> Lista()
         {
             //List<Person> person = await _context.Persons.ToListAsync();
             //return View(person);
             var list = await _context.People
          .Join(_context.Users,
                person => person.IdPerson,      // Presumiblemente tienes una propiedad Id en Person
                user => user.IdPerson,    // Suponiendo que IdPerson en User es una FK a Person
                (person, user) => new
                {
                    FullName = person.Names + " " + person.Lastname,
                    Email = person.Email,
                    Role = user.Role
                })
              .ToListAsync();

             return View(list);
         }*/
        [Authorize(Roles = "Principal,Administrador")]
        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            var list = await _context.People
                 .Join(_context.Users,
                       person => person.IdPerson,
                       user => user.IdPerson,
                       (person, user) => new
                       {
                           IdPerson = person.IdPerson,
                           FullName = person.Names + " " + person.Lastname,
                           Email = person.Email,
                           Role = user.Role,
                           Status = person.Status // Agrega el estado de la persona al resultado
                       })
                 .Where(x => x.Status == 1) // Filtrar por estado activo
                 .ToListAsync();

            return View(list);
        }
        //agregado
        // Nueva acción para ver las notificaciones asociadas a una persona
        public async Task<IActionResult> Notificaciones(int idPerson)
        {
            var person = await _context.People
                .Include(p => p.Notifications2) // Carga las notificaciones de la persona
                .FirstOrDefaultAsync(p => p.IdPerson == idPerson);

            if (person == null)
            {
                return NotFound();
            }

            ViewData["FullName"] = $"{person.Names} {person.Lastname}";
            return View(person.Notifications2); // Envía la lista de notificaciones a la vista
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var person = await _context.People.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }

            person.Status = 0; // Cambiar el estado a inactivo

            // Actualizar el estado del usuario asociado
            var user = await _context.Users.FirstOrDefaultAsync(u => u.IdPerson == id);
            if (user != null)
            {
                user.Status = 0;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Lista));
        }



    }
}

ProyectoColProfesionales/Views/Persona/Create.cshtml
@model ProyectoColProfesionales.Models.PersonModel

@{
    ViewData["Title"] = "Formulario Persona";
}
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@3.0.1/dist/css/multi-select-tag.css">
<script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@3.0.1/dist/js/multi-select-tag.js"></script>
<h1>@ViewData["Title"]</h1>
<form asp-action="Create" method="post" class="user-form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Names" class="control-label">Nombre</label>
            <input asp-for="Names" class="form-control" placeholder="Nombre">
            <span asp-validation-for="Names" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Lastname" class="control-label">Primer Apellido</label>
            <input asp-for="Lastname" class="form-control" placeholder="Primer Apellido">
            <span asp-validation-for="Lastname" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="SecondLastName" class="control-label">Segundo Apellido</label>
            <input asp-for="SecondLastName" class="form-control" placeholder="Segundo Apellido">
            <span asp-validation-for="SecondLastName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="IdentityNumber" class="control-label">C.I.</label>
            <input asp-for="IdentityNumber" class="form-control" placeholder="Cédula de Identidad">
            <span asp-validation-for="IdentityNumber" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="PhoneNumber" class="control-label">Número de Celular</label>
            <input asp-for="PhoneNumber" class="form-control" placeholder="Número de Celular">
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email" class="control-label">Correo Electrónico</label>
            <input asp-for="Email" class="form-control" placeholder="Correo Electrónico">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label for="role" class="control-label">Cargo</label>
        <select id="role" name="Role" class="form-control">
            <option value="Principal">Principal</option>
            <option value="Secundario">Secundario</option>
        </select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <button type="button" onclick="location.href='@Url.Action("Lista", "Persona")'" class="btn btn-secondary">Cancelar</button>

    </div>
</form>

ProyectoColProfesionales/Views/Persona/Lista.cshtml
@model IEnumerable<dynamic>
@{
    ViewData["Title"] = "Lista de Usuarios";
}
<link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">



<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col-md-10">
                <h6 class="m-0 font-weight-bold text-primary">Usuarios</h6>
            </div>
            <div class="col-md-2 text-right">
                <a href="@Url.Action("Create", "Persona")" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Registrar Usuario</span>
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nombre completo</th>
                        <th>Email</th>
                        <th>Rol</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.FullName</td>
                            <td>@item.Email</td>
                            <td>@item.Role</td>
                            <td style="display: flex; justify-content: center;">
                                <form asp-action="Delete" method="post" class="deleteForm">
                                    <input type="hidden" name="id" value="@item.IdPerson" />
                                    <button type="submit" class="btn btn-danger deleteButton" style="margin: 5px 5px;">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                language: {
                    //"decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
            $('.deleteForm').on('submit', function (e) {
                var confirmation = confirm('¿Estás seguro de que quieres eliminar este usuario?');
                if (!confirmation) {
                    e.preventDefault();
                }
            });
        });
        
    </script>
}

ProyectoColProfesionales/Views/Persona/Notificaciones.cshtml
@model IEnumerable<ProyectoColProfesionales.Models.DB1.Notification2>

@{
    ViewData["Title"] = "Notificaciones de Persona";
}
@* agregado *@
<h2>Notificaciones de @ViewData["FullName"]</h2>

<table class="table">
    <thead>
        <tr>
            <th>Mensaje</th>
            <th>Fecha 1</th>
            <th>Fecha 2</th>
            <th>Fecha 3</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var notification in Model)
        {
            <tr>
                <td>@notification.Message</td>
                <td>@notification.Date1?.ToString("dd/MM/yyyy")</td>
                <td>@notification.Date2?.ToString("dd/MM/yyyy")</td>
                <td>@notification.Date3?.ToString("dd/MM/yyyy")</td>
                <td>@notification.Status</td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-action="Lista">Volver a la lista de personas</a>
</p>